export enum InventoryMovementSource {

  MANUAL = 'MANUAL',

  PURCHASE_ORDER = 'PURCHASE_ORDER',

  SALES_ORDER = 'SALES_ORDER',

  STOCK_TRANSFER = 'STOCK_TRANSFER',

  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',

  PRODUCTION_ORDER = 'PRODUCTION_ORDER',

  INVENTORY_COUNT = 'INVENTORY_COUNT',

  CUSTOMER_RETURN = 'CUSTOMER_RETURN',

  SUPPLIER_RETURN = 'SUPPLIER_RETURN',

}