name: beer-control

services:
  postgres:
    image: postgres:17

    container_name: beer-control-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: beer_control
      POSTGRES_USER: beer_control
      POSTGRES_PASSWORD: beer_control

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beer_control"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: